### ISSUE TITLE
Windows Phone YouTube uses /feeds/api/playlists/snippets to search for playlists, but crashed the server

### ISSUE THREAD

**Issue by NLogDEV** [ftde0/yt2009#105]
Here's the crash log for it:

(-cps) euros+2024 clean fetch 1720017116405
URL: /feeds/api/channels?alt=json&q=euros%2b2024&start-index=1&max-results=10&safeSearch=moderate&restriction=GB
URL: /feeds/api/playlists/snippets?alt=json&q=euros%2b2024&start-index=1&max-results=10&safeSearch=moderate&restriction=GB
/yt2009/back/yt2009playlists.js:115
                let playlistArray = r.contents.twoColumnBrowseResultsRenderer
                                               ^
TypeError: Cannot read properties of undefined (reading 'twoColumnBrowseResultsRenderer')
    at /yt2009/back/yt2009playlists.js:115:48
    at /yt2009/back/yt2009playlists.js:26:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by upintheairsheep** [comment]
https://web.archive.org/web/*/https://m.google.com/youtube/* - here's the Windows Mobile (pre Winphone) YT apps

**Comment by NLogDEV** [comment]
Issue fixed since long time ago.
