### ISSUE TITLE
Problems.

### ISSUE THREAD

**Issue by Defreezer** [ftde0/yt2009#108]
Windows 7 64 bit with compatible dependencies installed: `Node.js 12.9.0`, `Git 2.39.1`, `ffmpeg essentials 7.0.1`, `ImageMagick 6.9.13.12 x64`. `Powershell 5.1 1005`.
Installed imagemagick 6.9.13.12 x64 along with its legacy tools (convert.exe): https://imagemagick.org/archive/binaries/
Made sure Imagemagick's install folder was in Windows' PATH Environment Variables field and that said folder contains `CORE_RL_magick_.dll`, `CORE_RL_wand_.dll` and `convert.exe`.

Opened CMD, started Powershell, then:

```
git clone https://github.com/ftde0/yt2009
cd "C:\PATH\TO\yt2009"
npm install node-fetch@2
npm install --save readline-sync
npm install express
npm install ytdl-core
npm install google-protobuf
npm install maxmind-db-reader
npm install node-html-parser
npm install encoding
npm install bufferutil
npm install utf-8-validate
node yt2009setup.js
node post_config_setup.js
cd back
node backend.js
```

Then I ran it by typing the XXX.X.X.X:XX localhost IP + port set in "node yt2009setup.js" into my browser.
When I tried to watch a video, the instance stopped with the following log:

```
RangeNotSatisfiableError: Range Not Satisfiable
    at createHttpError (C:\Users\User\yt2009\node_modules\send\index.js:984:7)
    at SendStream.error (C:\Users\User\yt2009\node_modules\send\index.js:270:31)
    at SendStream.send (C:\Users\User\yt2009\node_modules\send\index.js:666:19)
    at onstat (C:\Users\User\yt2009\node_modules\send\index.js:725:10)
    at FSReqCallback.oncomplete (fs.js:167:5)
retry_video video: Error: Status code: 403
retry_video audio: Error: Status code: 403
_http_outgoing.js:485
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
 [90m    at ServerResponse.setHeader (_http_outgoing.js:485:11) [39m
    at ServerResponse.header (C:\Users\User\yt2009\node_modules\ [4mexpress [24m\lib\response.
js:795:10)
    at ServerResponse.contentType (C:\Users\User\yt2009\node_modules\ [4mexpress [24m\lib\resp
onse.js:625:15)
    at ServerResponse.sendStatus (C:\Users\User\yt2009\node_modules\ [4mexpress [24m\lib\respo
nse.js:374:8)
    at PassThrough.<anonymous> (C:\Users\User\yt2009\back\backend.js:2535:17)
 [90m    at PassThrough.emit (events.js:214:15) [39m
 [90m    at PassThrough.emit (events.js:209:13) [39m
    at ClientRequest.<anonymous> (C:\Users\User\yt2009\node_modules\ [4mminiget [24m\dist\inde
x.js:211:28)
 [90m    at Object.onceWrapper (events.js:297:20) [39m
 [90m    at ClientRequest.emit (events.js:209:13) [39m
 
 C:\Users\User\yt2009\back>
```

Not sure what's going on.

**Comment by gohoski** [comment]
Apply this [pull](https://github.com/fent/node-ytdl-core/pull/1217) by running `npm install "git+ssh://git@github.com:khlevon/node-ytdl-core.git#v4.11.4-patch.2"` and try another video (clear the cache in the assets folder if needed).

**Comment by gohoski** [comment]
Hm. Try to replace the
```json
"ytdl-core": "latest"
```
line in the `package.json` file with this:
```json
"ytdl-core": "git+ssh://git@github.com:khlevon/node-ytdl-core.git#v4.11.4-patch.2"
```
And run `npm install`

**Comment by ftde0** [comment]
a commit was just released addressing some of the playback issues faced lately: https://github.com/ftde0/yt2009/commit/55faf2e1246f5716d5db3423ce45dbab124da3f8

try updating.

also, lines with `npm WARN` are - as the name implies - warnings. warnings that won't affect yt2009's functionality.

**Comment by ftde0** [comment]
alright! closing for now, feel free to reopen when something does end up happening again relating to those.
