### ISSUE TITLE
Getting 'Range Not Satisfiable' Error

### ISSUE THREAD

**Issue by CrazyMew37** [ftde0/yt2009#110]
Hello. I use a Windows 11 PC and I'm currently attempting to run yt2009, but any video I try to watch throws me this following error:

```
RangeNotSatisfiableError: Range Not Satisfiable
    at createHttpError (C:\Users\young\Downloads\yt2009-main\node_modules\send\index.js:984:7)
    at SendStream.error (C:\Users\young\Downloads\yt2009-main\node_modules\send\index.js:270:31)
    at SendStream.send (C:\Users\young\Downloads\yt2009-main\node_modules\send\index.js:666:19)
    at onstat (C:\Users\young\Downloads\yt2009-main\node_modules\send\index.js:725:10)
    at FSReqCallback.oncomplete (node:fs:198:5)
```

This happens for both dev and prod, and I cannot watch any video whatsoever. Usually, this error does not crash yt2009. How can I solve this bug?

**Comment by CrazyMew37** [comment]
Alright, I just updated my folder, and it works! Thank you!
