### ISSUE TITLE
Attempt to connect to mobile app fails

### ISSUE THREAD

**Issue by hikeri** [ftde0/yt2009#162]
When trying to connect to the YouTube 2.1 app, this error appears in my server console:
```
TypeError: Cannot read properties of undefined (reading '0')
    at Object.isAuthorized (/yt2009/back/yt2009mobileauths.js:22:47)
    at Object.feeds (/yt2009/back/yt2009mobile.js:499:25)
    at /yt2009/back/backend.js:1844:19
    at Layer.handle [as handle_request] (/yt2009/node_modules/express/lib/router/layer.js:95:5)
    at next (/yt2009/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/yt2009/node_modules/express/lib/router/route.js:119:3)
    at Layer.handle [as handle_request] (/yt2009/node_modules/express/lib/router/layer.js:95:5)
    at /yt2009/node_modules/express/lib/router/index.js:284:15
    at param (/yt2009/node_modules/express/lib/router/index.js:365:14)
    at param (/yt2009/node_modules/express/lib/router/index.js:376:14)
```
I use the docker version and proxy it through nginx

**Comment by ftde0** [comment]
you've enabled YT2009_GDATA_AUTH without adding any tokens. for a locally hosted instance for yourself (inaccessible from the outside) you don't need to enable gdata auth.

**Comment by ftde0** [comment]
that's strange then. i'll get around to fixing that for the newer version. thanks for the report!

**Comment by ftde0** [comment]
should be good now. can you update your yt2009 and check? feel free to close if all working.

**Comment by ftde0** [comment]
you shouldn't need to use web authorization if you don't plan on using gdata_auth.
can you open this url: `view-source:http://<your_instance_url>/feeds/api/standardfeeds/recently_featured` and send the response here?
