### ISSUE TITLE
APK Issue

### ISSUE THREAD

**Issue by coolgamer3957** [ftde0/yt2009#17]
I did everything right but when i try to connect on the yt app it displays this on cmd:
() sg32eS1XDi8 clean fetch 1700573412298
[yt2009_error] comments parser error TypeError: Cannot read properties of undefined (reading 'forEach')
    at Object.comments_parser (C:\Users\Admin\yt2009\back\yt2009utils.js:73:50)
    at C:\Users\Katika\yt2009\back\yt2009html.js:2386:37
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[yt2009_error] comments parser error TypeError: Cannot read properties of undefined (reading 'forEach')
    at Object.comments_parser (C:\Users\Admin\yt2009\back\yt2009utils.js:73:50)
    at C:\Users\Katika\yt2009\back\yt2009html.js:2389:37
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Then the app says there was a problem with your network?

**Comment by FurblandChannel** [comment]
Is the host set up correctly in the config?
