### ISSUE TITLE
RangeNotSatisfiableError: Range Not Satisfiable

### ISSUE THREAD

**Issue by starterbeeee** [ftde0/yt2009#50]
```
() Alw5hs0chj0 z cache (1706270511528)
() channel channel/UCPDXXXJj9nax0fr0Wfc048g
RangeNotSatisfiableError: Range Not Satisfiable
    at createHttpError (G:\runstuff\yt2009-main\node_modules\send\index.js:984:7)
    at SendStream.error (G:\runstuff\yt2009-main\node_modules\send\index.js:270:31)
    at SendStream.send (G:\runstuff\yt2009-main\node_modules\send\index.js:666:19)
    at onstat (G:\runstuff\yt2009-main\node_modules\send\index.js:725:10)
    at FSReqCallback.oncomplete (node:fs:202:5)
```
Dosen't crash but fails to load a video on web, video is Alw5hs0chj0.

**Comment by starterbeeee** [comment]
Shortly after i said that, it crashed on a different video; i restarted it and went to that same video and it loaded fine, then i went back to the video where the RangeNotSatisfiableError occurred and:
```
G:\runstuff\yt2009-main\node_modules\miniget\dist\index.js:206
                let err = new Miniget.MinigetError(`Status code: ${res.statusCode}`, res.statusCode);
                          ^

MinigetError: Status code: 410
    at ClientRequest.<anonymous> (G:\runstuff\yt2009-main\node_modules\miniget\dist\index.js:206:27)
    at Object.onceWrapper (node:events:633:26)
    at ClientRequest.emit (node:events:518:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:535:22)
    at TLSSocket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5) {
  statusCode: 410
}
```

**Comment by ftde0** [comment]
the video is age restricted; those don't work with yt2009. this is a known issue but unsure if much can be done about it.

close if no further questions.

**Comment by starterbeeee** [comment]
Alright, thanks!

**Comment by starterbeeee** [comment]
Maybe add a message that tells you the video is age-restricted on the frontend?
