### ISSUE TITLE
Crashes upon trying to view a channel or video

### ISSUE THREAD

**Issue by VideoGameSmash12** [ftde0/yt2009#52]
```none
/home/videogamesm12/youtube2009/yt2009/back/cache_dir/ryd_cache_manager.js:26
                    callback(utils.custom_rating_round(response.rating))
                                                                ^

TypeError: Cannot read properties of undefined (reading 'rating')
    at /home/videogamesm12/youtube2009/yt2009/back/cache_dir/ryd_cache_manager.js:26:65
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by ftde0** [comment]
try pulling the latest commit https://github.com/ftde0/yt2009/commit/f815a98a1546b48f266f5e880b4d7583839d2b7a. this seems to be related to the return youtube dislike's outage which didn't happen for that long before in yt2009's history of defaulting ryd.

**Comment by ftde0** [comment]
does the error crash the server as a whole? doesn't do that on my end

**Comment by VideoGameSmash12** [comment]
It does.

**Comment by ftde0** [comment]
https://github.com/ftde0/yt2009/commit/6ad12022078e742e8bddcd8db42dce0844a6d887 should do it.

**Comment by VideoGameSmash12** [comment]
Switching back and forth between videos on the channel page (possibly during playback, I'm not sure) also sometimes invokes an error that looks like this that crashes the entire web server:

```none
node:_http_outgoing:703
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (node:_http_outgoing:703:11)
    at ServerResponse.header (/home/videogamesm12/youtube2009/yt2009/node_modules/express/lib/response.js:794:10)
    at ServerResponse.location (/home/videogamesm12/youtube2009/yt2009/node_modules/express/lib/response.js:915:15)
    at ServerResponse.redirect (/home/videogamesm12/youtube2009/yt2009/node_modules/express/lib/response.js:953:18)
    at /home/videogamesm12/youtube2009/yt2009/back/backend.js:1102:17
    at WriteStream.<anonymous> (/home/videogamesm12/youtube2009/yt2009/back/yt2009utils.js:909:13)
    at WriteStream.emit (node:events:531:35)
    at finish (node:internal/streams/writable:946:10)
    at finishMaybe (node:internal/streams/writable:934:9)
    at WritableState.onConstructed (node:internal/streams/writable:380:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

**Comment by VideoGameSmash12** [comment]
Secondly, [this video](https://www.youtube.com/watch?v=sbU-gZFrRsM) seems to cause the backend to crash due to the ID not matching a defined regex pattern:

```none
/home/videogamesm12/youtube2009/yt2009/node_modules/ytdl-core/lib/url-utils.js:40
    throw TypeError(`Video id (${id}) does not match expected ` +
          ^

TypeError: Video id (sbUgZFrRsM) does not match expected format (/^[a-zA-Z0-9-_]{11}$/)
    at exports.getURLVideoID (/home/videogamesm12/youtube2009/yt2009/node_modules/ytdl-core/lib/url-utils.js:40:11)
    at exports.getVideoID (/home/videogamesm12/youtube2009/yt2009/node_modules/ytdl-core/lib/url-utils.js:61:20)
    at exports.<computed> [as getInfo] (/home/videogamesm12/youtube2009/yt2009/node_modules/ytdl-core/lib/info.js:484:29)
    at /home/videogamesm12/youtube2009/yt2009/back/backend.js:2296:18
    at Layer.handle [as handle_request] (/home/videogamesm12/youtube2009/yt2009/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/videogamesm12/youtube2009/yt2009/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/videogamesm12/youtube2009/yt2009/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/videogamesm12/youtube2009/yt2009/node_modules/express/lib/router/layer.js:95:5)
    at /home/videogamesm12/youtube2009/yt2009/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/videogamesm12/youtube2009/yt2009/node_modules/express/lib/router/index.js:346:12)
```

**Comment by ftde0** [comment]
> Secondly, [this video](https://www.youtube.com/watch?v=sbU-gZFrRsM) seems to cause the backend to crash due to the ID not matching a defined regex pattern:

that's an issue with ytdl, but what looks like is happening is that you're passing a 10-character ID to ytdl.

comparing with the link you sent:
> `sbU-gZFrRsM`

and the id ytdl receives:

> `sbUgZFrRsM`

the difference is there.

> Switching back and forth between videos on the channel page (possibly during playback, I'm not sure) also sometimes invokes an error that looks like this that crashes the entire web server:

will commit a fix shortly.

**Comment by ftde0** [comment]
hi, please report back on whether the issue's fixed so it can be closed.
