### ISSUE TITLE
Comments parser error

### ISSUE THREAD

**Issue by starterbeeee** [ftde0/yt2009#53]
```
[yt2009_error] comments parser error TypeError: Cannot read properties of undefined (reading 'forEach')
    at Object.comments_parser (G:\SRVDTA\yt2009-main\back\yt2009utils.js:73:50)
    at G:\SRVDTA\yt2009-main\back\yt2009html.js:2377:37
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[yt2009_error] comments parser error TypeError: Cannot read properties of undefined (reading 'forEach')
    at Object.comments_parser (G:\SRVDTA\yt2009-main\back\yt2009utils.js:73:50)
    at G:\SRVDTA\yt2009-main\back\yt2009html.js:2380:37
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[yt2009_error] comments parser error TypeError: Cannot read properties of undefined (reading 'forEach')
    at Object.comments_parser (G:\SRVDTA\yt2009-main\back\yt2009utils.js:73:50)
    at G:\SRVDTA\yt2009-main\back\yt2009html.js:2377:37
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[yt2009_error] comments parser error TypeError: Cannot read properties of undefined (reading 'forEach')
    at Object.comments_parser (G:\SRVDTA\yt2009-main\back\yt2009utils.js:73:50)
    at G:\SRVDTA\yt2009-main\back\yt2009html.js:2380:37
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[yt2009_error] comments parser error TypeError: Cannot read properties of undefined (reading 'commentRenderer')
    at parseITComment (G:\SRVDTA\yt2009-main\back\yt2009utils.js:101:61)
    at G:\SRVDTA\yt2009-main\back\yt2009utils.js:85:25
    at Array.forEach (<anonymous>)
    at G:\SRVDTA\yt2009-main\back\yt2009utils.js:84:34
    at Array.forEach (<anonymous>)
    at Object.comments_parser (G:\SRVDTA\yt2009-main\back\yt2009utils.js:73:50)
    at G:\SRVDTA\yt2009-main\back\yt2009html.js:2377:37
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[yt2009_error] comments parser error TypeError: Cannot read properties of undefined (reading 'commentRenderer')
    at parseITComment (G:\SRVDTA\yt2009-main\back\yt2009utils.js:101:61)
    at G:\SRVDTA\yt2009-main\back\yt2009utils.js:85:25
    at Array.forEach (<anonymous>)
    at G:\SRVDTA\yt2009-main\back\yt2009utils.js:84:34
    at Array.forEach (<anonymous>)
    at Object.comments_parser (G:\SRVDTA\yt2009-main\back\yt2009utils.js:73:50)
    at G:\SRVDTA\yt2009-main\back\yt2009html.js:2380:37
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
Happened after mobile loaded the recommendations, version 2.0.26.

**Comment by starterbeeee** [comment]
Came across this as well:
```
TypeError: Cannot read properties of undefined (reading 'includes')
    at checkBaseline (G:\SRVDTA\yt2009-main\back\backend.js:1058:34)
    at G:\SRVDTA\yt2009-main\back\backend.js:1073:8
    at Layer.handle [as handle_request] (G:\SRVDTA\yt2009-main\node_modules\express\lib\router\layer.js:95:5)
    at next (G:\SRVDTA\yt2009-main\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (G:\SRVDTA\yt2009-main\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (G:\SRVDTA\yt2009-main\node_modules\express\lib\router\layer.js:95:5)
    at G:\SRVDTA\yt2009-main\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (G:\SRVDTA\yt2009-main\node_modules\express\lib\router\index.js:346:12)
    at next (G:\SRVDTA\yt2009-main\node_modules\express\lib\router\index.js:280:10)
    at rawParser (G:\SRVDTA\yt2009-main\node_modules\body-parser\lib\types\raw.js:67:7)
baseline h264 req /channel_fh264_getvideo?v=ctvdxiPJKH4
TypeError: Cannot read properties of undefined (reading 'includes')
    at checkBaseline (G:\SRVDTA\yt2009-main\back\backend.js:1058:34)
    at G:\SRVDTA\yt2009-main\back\backend.js:1073:8
    at Layer.handle [as handle_request] (G:\SRVDTA\yt2009-main\node_modules\express\lib\router\layer.js:95:5)
    at next (G:\SRVDTA\yt2009-main\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (G:\SRVDTA\yt2009-main\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (G:\SRVDTA\yt2009-main\node_modules\express\lib\router\layer.js:95:5)
    at G:\SRVDTA\yt2009-main\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (G:\SRVDTA\yt2009-main\node_modules\express\lib\router\index.js:346:12)
    at next (G:\SRVDTA\yt2009-main\node_modules\express\lib\router\index.js:280:10)
    at rawParser (G:\SRVDTA\yt2009-main\node_modules\body-parser\lib\types\raw.js:67:7)
```
On video id `ctvdxiPJKH4`, after clicking HQ on the app.

**Comment by ftde0** [comment]
looks like you've got a commentViewModel experiment which isn't available to everyone yet (not to me) so i can't really test and fix. will do once i get it so i can properly do so.

**Comment by ftde0** [comment]
the issue should be fixed with https://github.com/ftde0/yt2009/commit/0c9189951d4b3092a0196f51b464f123536165a8. please report back on whether it is. feel free to close if so.
