### ISSUE TITLE
it crashes when trying to watch anything or view a channel

### ISSUE THREAD

**Issue by imjustkita** [ftde0/yt2009#60]
uhhh yeah, idk maybe i'm stupid or something that's also a possibility

```
(node:10172) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

    ==========

    yt2009 - dev

    ==========
    launch time: 20:24

received 25 videos from master
added 50 comments from master
() mainpage 1710012293424
() mainpage 1710012294987
() channel user/winslashfail
C:\yt2009\back\yt2009channels.js:135
        data.id = r.header.c4TabbedHeaderRenderer.channelId
                                                  ^

TypeError: Cannot read properties of undefined (reading 'channelId')
    at Object.parse_main_response (C:\yt2009\back\yt2009channels.js:135:51)
    at C:\yt2009\back\yt2009channels.js:83:26
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v21.7.1
```

no kurwa nie wiem

**Comment by ftde0** [comment]
co wywala ogladajac filmiki? podrzucisz swoje yt2009constants.json? tylko swoje ip wywal bo tam moze byc

**Comment by imjustkita** [comment]
no probujac ogladac filmy wlasnie to wywala i sie zamyka
[yt2009constants.json](https://github.com/ftde0/yt2009/files/14548346/yt2009constants.json)

**Comment by ftde0** [comment]
dobra dzk udało mi się odtworzyć, zrobię coś z tym za dnia bo coś testują i psuje

**Comment by ftde0** [comment]
po update powinno być ok, daj znać jak wszystko ok to mozna zamknąć

**Comment by imjustkita** [comment]
yup, teraz działa dobrze, dzięki

**Comment by ftde0** [comment]
spk, dzięki za issue!!
