### ISSUE TITLE
Instance keeps crashing

### ISSUE THREAD

**Issue by FurblandChannel** [ftde0/yt2009#64]
Instance (being run out of docker) occasionally crashes with 
```03/22/2024, 12:32:53:
/yt2009/back/backend.js:1109
03/22/2024, 12:32:53:
let vidLink = vid.replace("../", "/")
03/22/2024, 12:32:53:
^
03/22/2024, 12:32:53:
03/22/2024, 12:32:53:
TypeError: vid.replace is not a function
03/22/2024, 12:32:53:
at /yt2009/back/backend.js:1109:31
03/22/2024, 12:32:53:
at PassThrough. (/yt2009/back/yt2009utils.js:969:17)
03/22/2024, 12:32:53:
at PassThrough.emit (node:events:518:28)
03/22/2024, 12:32:53:
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
03/22/2024, 12:32:53:
```

**Comment by ftde0** [comment]
will fix tomorrow. thanks for the report!

**Comment by ftde0** [comment]
the issue should be solved. reopen if still happening after updates.

**Comment by FurblandChannel** [comment]
reopening as issue of a similar vein has been discovered
```
05/17/2024, 19:39:32:
/yt2009/back/yt2009utils.js:790
05/17/2024, 19:39:32:
        response.contents.twoColumnBrowseResultsRenderer.tabs.forEach(tab => {
05/17/2024, 19:39:32:
                          ^
05/17/2024, 19:39:32:
05/17/2024, 19:39:32:
TypeError: Cannot read properties of undefined (reading 'twoColumnBrowseResultsRenderer')
05/17/2024, 19:39:32:
    at Object.channelJumpTab (/yt2009/back/yt2009utils.js:790:27)
05/17/2024, 19:39:32:
    at /yt2009/back/yt2009channels.js:450:42
05/17/2024, 19:39:32:
    at /yt2009/back/yt2009utils.js:784:13
05/17/2024, 19:39:32:
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
