### ISSUE TITLE
i getting this error

### ISSUE THREAD

**Issue by zjzjaqka** [ftde0/yt2009#84]
() tROZCmlWtOc clean fetch 1715048083995
[dev] using comments_viewmodel_parser instead
[dev] using comments_viewmodel_parser instead
(exp_related) padrinhos  before:2010-04-01 clean fetch 1715048087967
[dev] using comments_viewmodel_parser instead
[dev] using comments_viewmodel_parser instead

C:\yt2009-main\node_modules\node-fetch\lib\index.js:1501
                        reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
                               ^
FetchError: request to https://returnyoutubedislikeapi.com/votes?videoId=tROZCmlWtOc failed, reason: unable to verify the first certificate
    at ClientRequest.<anonymous> (C:\yt2009-main\node_modules\node-fetch\lib\index.js:1501:11)
    at ClientRequest.emit (node:events:520:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
looks like return youtube dislike api doesnt load

**Comment by ftde0** [comment]
sounds like a proxy issue

**Comment by zjzjaqka** [comment]
how to fix it?

**Comment by zjzjaqka** [comment]
how i fix it?

**Comment by VictorFilimonov** [comment]
same. FetchError: request to https://yt3.ggpht.com/ytc/AIdro_kVdNayYfyZR_2sOpMR4rWkzxo24pV5CwTS0EkrU_ZvKA=s88-c-k-c0x00ffffff-no-rj failed

**Comment by zjzjaqka** [comment]
How do i fix it?

**Comment by ftde0** [comment]
@zjzjaqka please don't spam the issue with the same comment. try turning off any proxys, vpns or anything that may interfere with your network.
@VictorFilimonov can you post the full log at request time?

**Comment by VictorFilimonov** [comment]
/yt2009/node_modules/node-fetch/lib/index.js:1501
			reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
			       ^
FetchError: request to https://yt3.ggpht.com/ytc/AIdro_noXk-sAWIShpLBGYJF8UBkxLqTVpEyKt6wc8RbLpI9oZ9K3fTx2m76BhURFUTEFDYu2Q=s88-c-k-c0x00ffffff-no-rj failed, reason: 
    at ClientRequest.<anonymous> (/yt2009/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:519:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
Node.js v20.13.0
    ==========
    yt2009 - dev
    ==========
    launch time: 16:56
        
received 25 videos from master
() channel channel/UChhSV3sWNQ_aoXM0E5PC4sw
added 50 comments from master
() channel channel/UC6P-EyOz-8kcT5TCK-qwkrg
() channel channel/UCceEhLzjMtRZdXzIAmqlmKw
[dev] using comments_viewmodel_parser instead
[dev] using comments_viewmodel_parser instead
[yt2009_error] comments parser error TypeError: Cannot read properties of undefined (reading 'forEach')
    at Object.comments_parser (/yt2009/back/yt2009utils.js:124:50)
    at /yt2009/back/yt2009html.js:2509:37
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[yt2009_error] comments parser error TypeError: Cannot read properties of undefined (reading 'forEach')
    at Object.comments_parser (/yt2009/back/yt2009utils.js:124:50)
    at /yt2009/back/yt2009html.js:2512:37
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
() channel channel/UC0YAfKY19rHqhKFPW5d2sbQ
() channel channel/UCRGGcHedfSpmp-vFPvD2sCg
() channel channel/UCCO-E6TrEmZlH3bnUiTqyEw
() channel channel/UC7HRdxlamqpRVMPW6MBJlcQ
() channel channel/UCqSv69kjChrNvDWtB0lDzvg
[dev] using comments_viewmodel_parser instead
[dev] using comments_viewmodel_parser instead
() channel channel/UC3-eAm-eFDo_33A_ndphw2g
() channel channel/UC-fNVKLSSxGbsdq6F6Lxc-w
() channel channel/UCGXBE4SrNV0qCtLReBzym_g
[dev] using comments_viewmodel_parser instead
[dev] using comments_viewmodel_parser instead
() channel channel/UCG94rpZEA7WG1eN_UC8GsDA
[dev] using comments_viewmodel_parser instead
[dev] using comments_viewmodel_parser instead
() channel channel/UCYdhJ5dYfkAkEC9E832ZGzA
[dev] using comments_viewmodel_parser instead
[dev] using comments_viewmodel_parser instead
() channel channel/UCmI1CHFEr3HJyfDzeDkh5Kw
() channel channel/UCDdPJHmxHCJLH1sDyytCATw
[dev] using comments_viewmodel_parser instead
[dev] using comments_viewmodel_parser instead
() channel channel/UCCVmfCNYq2sEf3_jqRT5f7w
[dev] using comments_viewmodel_parser instead
[dev] using comments_viewmodel_parser instead
() channel channel/UCyHLnD9b92e7SyvfIU4dh5A
[dev] using comments_viewmodel_parser instead
[dev] using comments_viewmodel_parser instead
() channel channel/UCwmzbvi9B0CFKk1AUgxmdBA
[dev] using comments_viewmodel_parser instead
[dev] using comments_viewmodel_parser instead
() channel channel/UCjmCUJmzwjvFTB0u8CdepKw
() channel channel/UC-P-lcop9a4KtJ9p7waBSuA
[dev] using comments_viewmodel_parser instead
[dev] using comments_viewmodel_parser instead
() channel channel/UC-MZ2xH-YQfPbdwbOJO3Xog
[dev] using comments_viewmodel_parser instead
[dev] using comments_viewmodel_parser instead
() VIgSgLFwEMs clean fetch 1715187489886 
() channel channel/UCYEOZZvX1eAF3OzVgxxib9A
[dev] using comments_viewmodel_parser instead
() channel channel/UCb--64Gl51jIEVE-GLDAVTg
[dev] using comments_viewmodel_parser instead
[dev] using comments_viewmodel_parser instead
[dev] using comments_viewmodel_parser instead
() channel channel/UCGU5VWJgEccp4nB9ddnIrUw
() channel channel/UCRPFGlUXlAe7NQHKJv9Kx2g
() channel channel/UCmrQ8R-ZI6lWvmuDTaqXYPg
() channel channel/UC1pHR8moLz9QBu76wy60GHQ
() channel channel/UCUStfw15QWLasnIh8EDXknA
() channel channel/UCc82gWqNrRWLxtyujYHDNOQ
() channel channel/UCxubR_djWMzHIQrKpL6ynHw
() channel channel/UCnlyD7sPwlQ1Va5R7oy3evQ
[dev] using comments_viewmodel_parser instead
[dev] using comments_viewmodel_parser instead
() channel channel/UCWVYw5L3QkaECAI_VABM5WQ
[yt2009_error] comments parser error TypeError: Cannot read properties of undefined (reading 'forEach')
    at Object.comments_parser (/yt2009/back/yt2009utils.js:124:50)
    at /yt2009/back/yt2009html.js:2509:37
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by ftde0** [comment]
does the URL it's trying to request (https://yt3.ggpht.com/ytc/AIdro_noXk-sAWIShpLBGYJF8UBkxLqTVpEyKt6wc8RbLpI9oZ9K3fTx2m76BhURFUTEFDYu2Q=s88-c-k-c0x00ffffff-no-rj) open in your browser?

**Comment by ftde0** [comment]
probably an issue with your internet then, and unfortunately not much i can do to properly solve this issue (best i could do is probably to make it not crash and use some placeholder image). the image opens fine on my end.
![cn](https://github.com/ftde0/yt2009/assets/76792259/02bed2cf-f2a6-4380-ac12-9f41eee394fa)

this does sound similar to #4 though.

**Comment by ftde0** [comment]
weird, assuming there is nothing else running (no network monitoring software/nothing?) you can work around this by changing the "fetch" function in `/back/cache_dir/ryd_cache_manager.js` to:

``` 
"fetch": function(id, callback) {
     callback(5);
}
```

this IS however just a workaround to keep yt2009 from crashing and will show all videos having 5 stars. but it won't crash.

**Comment by zjzjaqka** [comment]
> weird, assuming there is nothing else running (no network monitoring software/nothing?) you can work around this by changing the "fetch" function in `/back/cache_dir/ryd_cache_manager.js` to:
> 
> ```
> "fetch": function(id, callback) {
>      callback(5);
> }
> ```
> 
> this IS however just a workaround to keep yt2009 from crashing and will show all videos having 5 stars. but it won't crash.

![Captura de tela 2024-05-08 173933](https://github.com/ftde0/yt2009/assets/148755598/2957a26e-0821-4bec-a04a-607ea8bbd70b)
![image](https://github.com/ftde0/yt2009/assets/148755598/a4360f76-23fe-4dbc-95e8-9546dfa3a2e8)
`C:\yt2009-main\back>  node backend.js
C:\yt2009-main\back\cache_dir\ryd_cache_manager.js:17
    "readCache": function(id) {
               ^

SyntaxError: Unexpected token ':'
    at wrapSafe (node:internal/modules/cjs/loader:1389:18)
    at Module._compile (node:internal/modules/cjs/loader:1425:20)
    at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
    at Module.load (node:internal/modules/cjs/loader:1287:32)
    at Module._load (node:internal/modules/cjs/loader:1103:12)
    at Module.require (node:internal/modules/cjs/loader:1310:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\yt2009-main\back\yt2009html.js:10:19)
    at Module._compile (node:internal/modules/cjs/loader:1480:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)

Node.js v22.1.0
`

**Comment by ftde0** [comment]
you seem to have forgotten the closing bracket, but upon further inspection i also forgot a character. the updated code to just drop in should look like this

```
"fetch": function(id, callback) {
     callback(5);
},
```

the difference is in the `,` at the end.

**Comment by zjzjaqka** [comment]
> you seem to have forgotten the closing bracket, but upon further inspection i also forgot a character. the updated code to just drop in should look like this
> 
> ```
> "fetch": function(id, callback) {
>      callback(5);
> },
> ```
> 
> the difference is in the `,` at the end.

![Captura de tela 2024-05-08 175130](https://github.com/ftde0/yt2009/assets/148755598/9c40a2ed-42fb-4e1f-bc73-4247e442e0aa)
C:\yt2009-main\back\cache_dir\ryd_cache_manager.js:1
}
^

SyntaxError: Unexpected token '}'
    at wrapSafe (node:internal/modules/cjs/loader:1389:18)
    at Module._compile (node:internal/modules/cjs/loader:1425:20)
    at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
    at Module.load (node:internal/modules/cjs/loader:1287:32)
    at Module._load (node:internal/modules/cjs/loader:1103:12)
    at Module.require (node:internal/modules/cjs/loader:1310:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\yt2009-main\back\yt2009html.js:10:19)
    at Module._compile (node:internal/modules/cjs/loader:1480:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)

Node.js v22.1.0

**Comment by zjzjaqka** [comment]
> you seem to have forgotten the closing bracket, but upon further inspection i also forgot a character. the updated code to just drop in should look like this
> 
> ```
> "fetch": function(id, callback) {
>      callback(5);
> },
> ```
> 
> the difference is in the `,` at the end.

![Captura de tela 2024-05-08 175351](https://github.com/ftde0/yt2009/assets/148755598/b735d513-126a-45e0-9efc-4d094697fdef)
 C:\yt2009-main\back>node backend.js
C:\yt2009-main\back\cache_dir\ryd_cache_manager.js:1
}
^

SyntaxError: Unexpected token '}'
    at wrapSafe (node:internal/modules/cjs/loader:1389:18)
    at Module._compile (node:internal/modules/cjs/loader:1425:20)
    at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
    at Module.load (node:internal/modules/cjs/loader:1287:32)
    at Module._load (node:internal/modules/cjs/loader:1103:12)
    at Module.require (node:internal/modules/cjs/loader:1310:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\yt2009-main\back\yt2009html.js:10:19)
    at Module._compile (node:internal/modules/cjs/loader:1480:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)

Node.js v22.1.0

**Comment by ftde0** [comment]
you have a lonely closing bracket at line 1 (the beginning of the script) that shouldn't be here. remove it

**Comment by zjzjaqka** [comment]
Which one?

**Comment by ftde0** [comment]
at the beginning, before `const fs =`... remove only the closing bracket

**Comment by zjzjaqka** [comment]
> at the beginning, before `const fs =`... remove only the closing bracket

![Captura de tela 2024-05-08 180142](https://github.com/ftde0/yt2009/assets/148755598/30772f15-d397-452c-8a3c-1068a31826b2)
C:\yt2009-main\back>  node backend.js
C:\yt2009-main\back\cache_dir\ryd_cache_manager.js:1
}
^

SyntaxError: Unexpected token '}'
    at wrapSafe (node:internal/modules/cjs/loader:1389:18)
    at Module._compile (node:internal/modules/cjs/loader:1425:20)
    at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
    at Module.load (node:internal/modules/cjs/loader:1287:32)
    at Module._load (node:internal/modules/cjs/loader:1103:12)
    at Module.require (node:internal/modules/cjs/loader:1310:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\yt2009-main\back\yt2009html.js:10:19)
    at Module._compile (node:internal/modules/cjs/loader:1480:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)

Node.js v22.1.0

**Comment by ftde0** [comment]
no no no don't remove the consts, put them back, this bracket is what i was talking about

![Screenshot_20240508-230422_Bromite](https://github.com/ftde0/yt2009/assets/76792259/d4032397-2b33-48d2-a291-e817cb74e6f4)

**Comment by zjzjaqka** [comment]
> no no no don't remove the consts, put them back, this bracket is what i was talking about
> 
> ![Screenshot_20240508-230422_Bromite](https://private-user-images.githubusercontent.com/76792259/329048357-d4032397-2b33-48d2-a291-e817cb74e6f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMDI2OTQsIm5iZiI6MTcxNTIwMjM5NCwicGF0aCI6Ii83Njc5MjI1OS8zMjkwNDgzNTctZDQwMzIzOTctMmIzMy00OGQyLWEyOTEtZTgxN2NiNzRlNmY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDIxMDYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3MzRhOGE3Njk1N2VkNmIzYzgxZGUwODUzZjk2NTYxODEwZDk5Y2MxZjI4OGU3NzEwYzQ2MGU1ZWNlNGMxYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fVVjbMfIImpx9oUgv1tNBOnVHKvuEtBdWrHrvbLSyJQ)

it worked! thank you.

**Comment by VictorFilimonov** [comment]
> probably an issue with your internet then, and unfortunately not much i can do to properly solve this issue (best i could do is probably to make it not crash and use some placeholder image). the image opens fine on my end. ![cn](https://private-user-images.githubusercontent.com/76792259/329012639-02bed2cf-f2a6-4380-ac12-9f41eee394fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDU5MDksIm5iZiI6MTcxNTI0NTYwOSwicGF0aCI6Ii83Njc5MjI1OS8zMjkwMTI2MzktMDJiZWQyY2YtZjJhNi00MzgwLWFjMTItOWY0MWVlZTM5NGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDA5MDY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0NTVlYzMzYmU1M2FkZTExMzM5MWUwNWFmNzI5MjkyMGJiMjZlYWY5OTU4MjI4OTAyMGY0MjMyYjBjYzg3NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sx3zyibiXUTUOrTjh10WKpo_dKP2mCwKwl2cJWP1q1U)
> 
> this does sound similar to #4 though.

Replace yt3.ggpht.com with yt3.googleusercontent.com/
