### ISSUE TITLE
errors while fetching the comments

### ISSUE THREAD

**Issue by VictorFilimonov** [ftde0/yt2009#86]
Log: 
```
[yt2009_error] comments parser error TypeError: Cannot read properties of undefined (reading 'forEach')
    at Object.comments_parser (C:\yt2009\back\yt2009utils.js:124:50)
    at C:\yt2009\back\yt2009html.js:2520:37
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[yt2009_error] comments parser error TypeError: Cannot read properties of undefined (reading 'forEach')
    at Object.comments_parser (C:\yt2009\back\yt2009utils.js:124:50)
    at C:\yt2009\back\yt2009html.js:2523:37
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


```

**Comment by ftde0** [comment]
this usually means the video just has no comments. this error will be a lil less sensitive in the future, but for now doesn't look like there's anything to worry about.
