### ISSUE TITLE
Crashes with file formats...

### ISSUE THREAD

**Issue by VictorFilimonov** [ftde0/yt2009#88]
Log
```
/yt2009/back/backend.js:4166
        let url = player.streamingData.formats[0].url
                                       ^
TypeError: Cannot read properties of undefined (reading 'formats')
    at handlePlayer (/yt2009/back/backend.js:4166:40)
    at /yt2009/back/backend.js:4270:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by VictorFilimonov** [comment]
And the problems with loading video 
```
/yt2009/node_modules/node-fetch/lib/index.js:1501
			reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
			       ^
FetchError: request to https://rr4---sn-p5qlsn7s.googlevideo.com/videoplayback?expire=1715365109&ei=lRA-Zr-jMpSSlu8PtfaYiAY&ip=3.129.111.220&id=o-AMPAOtklZcDpqg3d-8ZU_6yJtXMNrn926cwMGK5hA8tK&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=05&mm=31%2C29&mn=sn-p5qlsn7s%2Csn-p5qs7nzy&ms=au%2Crdu&mv=u&mvi=4&pl=23&bui=AWRWj2QEYuB4oJsN50dxuNXKAcl2zFQMc6N9dSkm-_Q9HRCa5W2liZj3so2gu9JhI5UmKqEAmSlPj3BK&vprv=1&svpuc=1&mime=video%2Fmp4&ns=plWc1iQ_Q8phIYOaOoUsm68Q&rqh=1&gir=yes&clen=2061568&ratebypass=yes&dur=43.467&lmt=1248461926534338&mt=1715342987&fvip=3&c=TVHTML5_SIMPLY_EMBEDDED_PLAYER&sefc=1&n=etYUrE9n9-rD7f7p-&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRAIgZMMM-3Wztrrv2BWsFOJ5Hp3BTALTSYIaIPyzAcXSaI8CIBDASYfclMhDjA7Y1M5C3AeFE-xXrqF-0Q9q1tgG0sNv&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AHWaYeowRQIhAN_Z0yWkDGE-yJoRNXzcZ6cZX3IXRn4JRIW52PqAERspAiA6xcOCn8UDAFEM-oD2VHIp6nwzC6p51N2mp-T5BSqp-g%3D%3D failed, reason: 
    at ClientRequest.<anonymous> (/yt2009/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:519:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}

```

**Comment by ftde0** [comment]
> ```
> /yt2009/back/backend.js:4166
>         let url = player.streamingData.formats[0].url
>                                        ^
> TypeError: Cannot read properties of undefined (reading 'formats')
>     at handlePlayer (/yt2009/back/backend.js:4166:40)
>     at /yt2009/back/backend.js:4270:9
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> ```


looks like you're trying to view an age-restricted video, those require login and use a bypass which is not 100% reliable. support for adding accounts for better age restrict bypass is planned.

> ```
> errno: 'ETIMEDOUT',
> code: 'ETIMEDOUT'
> ```

sorry, can't do anything about internet issues, especially when the link opens fine for me. the link is a direct video link, and unlike googleusercontent/ggpht i don't really see a way to bypass that aside from straight up not playing the video which is far from ideal.
