### ISSUE TITLE
Crash when trying to view any video or channel page

### ISSUE THREAD

**Issue by EpicSentry** [ftde0/yt2009#89]
I just installed yt2009 on a clean Debian 12 install and I get the following issue when i click on a channel page or a video:

    ==========

    yt2009 - dev

    ==========
    launch time: 22:42

received 25 videos from master
added 50 comments from master
(g8bv0oy) test clean fetch 1715895741233
(g8bv0oy) dbjPnXaacAU clean fetch 1715895745344
[dev] using comments_viewmodel_parser instead
() channel channel/UCXp1pqN0VP459pjypvK_Rww
[dev] using comments_viewmodel_parser instead
/home/user/yt2009/back/yt2009channels.js:135
        data.id = r.header.c4TabbedHeaderRenderer.channelId
                                                                              ^

TypeError: Cannot read properties of undefined (reading 'channelId')
    at Object.parse_main_response (/home/user/yt2009/back/yt2009channels.js:135:51)
    at /home/user/yt2009/back/yt2009channels.js:83:26
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.17.1

**Comment by ftde0** [comment]
hi!
does this happen on every video? if so, can you send your /back/yt2009constants.json? make sure to remove your IP from there before sending, it may be there.

**Comment by EpicSentry** [comment]
Hello, sorry for the delayed reply, here is the file you requested:
```user@pc:~$ cat /home/user/yt2009/back/yt2009constants.json
{"headers":{"accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9","cookie":"YSC=G9wtghNItis; __Secure-YEC=CgtwMElPZ09CRFZ0TSjl9ZmyBjIOCgJJRRIIEgQSAgsMIEs%3D; VISITOR_PRIVACY_METADATA=CgJJRRIIEgQSAgsMIEs%3D; VISITOR_INFO1_LIVE=; ","dnt":1,"sec-fetch-dest":"document","sec-fetch-mode":"navigate","sec-fetch-site":"same-origin","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0"},"comments_remove_future_phrases":["2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021","2022","2023","nostalgi","childhood","covid","reupload","memories","year","decade","young","2010s","2010's","lat","remember","old"],"cached_innertube_context":{"client":{"hl":"en","gl":"IE","remoteHost":"my public ip4","deviceMake":"","deviceModel":"","visitorData":"CgtwMElPZ09CRFZ0TSjl9ZmyBjIOCgJJRRIIEgQSAgsMIEs%3D","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0,gzip(gfe)","clientName":"WEB","clientVersion":"2.20240514.03.00","osName":"Windows","osVersion":"10.0","originalUrl":"https://www.youtube.com/","platform":"DESKTOP","clientFormFactor":"UNKNOWN_FORM_FACTOR","configInfo":{"appInstallData":"COX1mbIGEOevsAUQt--vBRD567AFEJaf_xIQi8-wBRDUoa8FEL2KsAUQiOOvBRD_37AFENuvrwUQro__EhDuoq8FEP_wsAUQp-OwBRCa8bAFENjdsAUQzdewBRDM364FEMnXsAUQnuSwBRCIh7AFENfprwUQgqL_EhDr27AFEKzqsAUQ2cmvBRCr5LAFEPPrsAUQ9KuwBRCd0LAFEPvasAUQ0-CwBRCj7bAFEOvo_hIQi-ywBRCr77AFENCNsAUQmvCvBRC3srAFEInorgUQt-r-EhCikrAFEIKisAUQ9Kn_EhDZ4LAFEPOhsAUQ7rOwBRDT4a8FEOfDsAUQqtiwBRDeiP8SENbnsAUQvvmvBRDqw68FEPXgsAUQ8JywBRCW8bAFELHcsAUQ8LKwBRCPxLAFEKe3sAUQg7-wBRCNzLAFEMnmsAUQlpWwBRDd6P4SENbdsAUQgsawBRC3q7AFEL22rgUQu9KvBRDj0bAFEMf9tyIQ1-CwBRDvzbAFEPnksAUQ1YiwBRDEzLAFEJCysAUQ99CwBRD2q7AFEJjxsAUQ_eCwBRD8hbAFEKzYsAUQ8-CwBRCA7bAFEPjSsAUQl4OwBRDJ968FEI3osAUQqJqwBRD_5LAFEKKBsAUQvZmwBRCM7rAFEM-osAUQ9eSwBRCmmrAFEMyu_xIQreOwBRDi1K4FEKXC_hIQ8uywBRClp_8SELKCsAUQvt-wBSogQ0FNU0VoVUpvTDJ3RE5Ia0JxQ1E5QXZMMUFRZEJ3PT0%3D"},"userInterfaceTheme":"USER_INTERFACE_THEME_LIGHT","browserName":"Firefox","browserVersion":"102.0","acceptHeader":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","deviceExperimentId":"ChxOek0yT1RjeE1qazJORE14TkRneU16TTBOUT09EOX1mbIGGOX1mbIG"}},"homepageCache_gaming":[{"id":"-zDffe_IHJw","title":"Modern Warfare 2 Camper's Search and Destroy 5 (UMP Russia)","uploaderUrl":"/user/ThatGuyWhoCamps","uploaderName":"ThatGuyWhoCamps","rating":"4.5","views":"75,748 views","time":"6:26"},{"id":"p7okapo0h0g","title":"CS:S | Funny Ninja Defuse by bSt'","uploaderUrl":"/user/MadeByBoOst","uploaderName":"MadeByBoOst","rating":"4.5","views":"2,248,395 views","time":"0:22"},{"id":"4TWRxbipAAU","title":"Download CS Source Non Steam No Torrent...","uploaderUrl":"/user/Dragon16508","uploaderName":"Dragon16508","rating":"4.5","views":"12,345 views","time":"1:20"},{"id":"0rmNDvUI5lU","title":"Call of Duty Modern Warfare 2 - Boosting Exposed!","uploaderUrl":"/user/Smoove7182954","uploaderName":"Smoove7182954","rating":"4.5","views":"712,634 views","time":"3:11"},{"id":"h0-nYVHyQWc","title":"Modern Warfare 2 Javelin Glitch","uploaderUrl":"/user/WhatEverHD","uploaderName":"WhatEverHD","rating":"4.5","views":"2,181,540 views","time":"3:08"},{"id":"PD24MkbHQrc","title":"Red Dead Redemption Official Trailer \"My Name is John Marston\"","uploaderUrl":"/user/RockstarGames","uploaderName":"RockstarGames","rating":"5","views":"3,754,507 views","time":"2:01"},{"id":"XFF9dwnH86o","title":"Super Mario 64 DS Walkthrough Part 43","uploaderUrl":"/user/superskarmory","uploaderName":"superskarmory","rating":"4.5","views":"268,978 views","time":"6:47"},{"id":"It6xj40UVRM","title":"Alex Day - Pokémon, What Happened To You?","uploaderUrl":"/c/alexday","uploaderName":"nerimon","rating":"4","views":"2,063,213 views","time":"5:05"},{"id":"bVOhPNvPyZc","title":"REAL Wii Bowling Ball?!?!!","uploaderUrl":"/user/ijustinereviews","uploaderName":"ijustinereviews","rating":"5","views":"80,503 views","time":"2:12"}],"homepageCache_top_favorited":[{"id":"NCP1oEbDqxE","title":"United State of MULTI-FANDOM","uploaderUrl":"/user/luckybiatch","uploaderName":"luckybiatch","rating":"5","views":"71,115 views","time":"3:46"},{"id":"tzWTcDydlpM","title":"BioShock 2 Launch Trailer","uploaderUrl":"/user/2kgamesinternational","uploaderName":"2kgamesinternational","rating":"5","views":"357,988 views","time":"3:20"},{"id":"dgj1l9vUyhU","title":"Nigerian player kung fu kicks greece player Kaita sent off","uploaderUrl":"/user/Crabscratcher","uploaderName":"Crabscratcher","rating":"4.5","views":"2,422,123 views","time":"0:26"}],"homepageCache_science_technology":[{"id":"PJyGgqV1ggM","title":"Nexus One software update - AndroidCentral.com","uploaderUrl":"/user/AndroidCentral","uploaderName":"AndroidCentral","rating":"4","views":"17,672 views","time":"2:28"},{"id":"ZHJDvZWrW3A","title":"The Great \"Android phones\" War ;)","uploaderUrl":"/user/AndroidHD","uploaderName":"AndroidHD","rating":"5","views":"145,303 views","time":"3:36"},{"id":"Bd9hNq4ZIqU","title":"Skype calling over 3G on iPhone - coming soon","uploaderUrl":"/user/SkypeConversations","uploaderName":"SkypeConversations","rating":"4","views":"61,696 views","time":"1:37"},{"id":"CTvBMt9Zsug","title":"Sony Ericsson Aspen","uploaderUrl":"/user/MobileGazette","uploaderName":"MobileGazette","rating":"4","views":"82,906 views","time":"2:29"},{"id":"g23e9e9zOVI","title":"blacksn0w","uploaderUrl":"/user/geohot","uploaderName":"geohot","rating":"5","views":"860,780 views","time":"0:53"},{"id":"vsQh1AT6qUE","title":"How to make Magnetic Fluid (ferro fluid)","uploaderUrl":"/user/HouseholdHacker","uploaderName":"HouseholdHacker","rating":"5","views":"234,750 views","time":"4:12"}],"homepageCache_howto_style":[{"id":"Yu4Qs1njM3c","title":"What Really Matters","uploaderUrl":"/user/bubzbeauty","uploaderName":"bubzbeauty","rating":"5","views":"681,119 views","time":"7:50"},{"id":"tR7h60fW-QA","title":"Fitness - Fat Slaughter Workout","uploaderUrl":"/user/charliejames1975","uploaderName":"charliejames1975","rating":"4.5","views":"960,951 views","time":"6:56"},{"id":"hFlJZwWzROo","title":"Miley Cyrus V-Day Hair Tutorial","uploaderUrl":"/user/DulceCandy87","uploaderName":"DulceCandy87","rating":"4.5","views":"632,837 views","time":"12:30"},{"id":"U5utl8LwXnA","title":"Look San Valentin: Romantico-Romantic look for Valentine","uploaderUrl":"/user/mymakeupcorner","uploaderName":"mymakeupcorner","rating":"5","views":"63,128 views","time":"9:02"},{"id":"rkxc-Y66isc","title":"What I'm Loving - January","uploaderUrl":"/c/ElleFowler","uploaderName":"ElleFowler","rating":"4","views":"548,278 views","time":"11:38"},{"id":"esDGzy50PDM","title":"January Favorites","uploaderUrl":"/user/juicystar07","uploaderName":"juicystar07","rating":"4.5","views":"637,532 views","time":"12:59"},{"id":"0rbCGctrerk","title":"Tutorial: Jailbreak para iPhone & iPod Touch Firmware 3.1.2 con RedSnow","uploaderUrl":"/user/yoguipod","uploaderName":"yoguipod","rating":"5","views":"21,608 views","time":"8:01"},{"id":"VQYPFg8UfjE","title":"how to paint flower","uploaderUrl":"/user/bonggorospe","uploaderName":"bonggorospe","rating":"4.5","views":"163,473 views","time":"4:38"}],"homepageCache_sports":[{"id":"wYz7k3YF9hQ","title":"NBA highlights from November 15th","uploaderUrl":"/user/NBA","uploaderName":"NBA","rating":"5","views":"138,400 views","time":"2:23"},{"id":"ivBnIOFx-m8","title":"R.I.P. Robert Enke (Bette Midler - The Rose)","uploaderUrl":"/user/Royal10999","uploaderName":"Royal10999","rating":"4.5","views":"180,610 views","time":"3:50"},{"id":"vu1zMV5j0fo","title":"Trevor Ariza loses shoe, Ron Artest tosses it into the stands","uploaderUrl":"/user/clutchfansDOTnet","uploaderName":"clutchfansDOTnet","rating":"5","views":"2,206,115 views","time":"0:45"},{"id":"aDlKoJ1r-V8","title":"NBA TV Top 10: November 20th","uploaderUrl":"/user/NBA","uploaderName":"NBA","rating":"5","views":"190,320 views","time":"2:59"},{"id":"7TlUO7flMCk","title":"Glock 26 (Chapter 2)","uploaderUrl":"/user/hickok45","uploaderName":"hickok45","rating":"5","views":"416,549 views","time":"12:06"},{"id":"9zAVc6Hgs7A","title":"Stony Brook Men's Soccer Semifinal Shootout","uploaderUrl":"/user/stonybrookseawolves","uploaderName":"stonybrookseawolves","rating":"4","views":"863,062 views","time":"3:02"},{"id":"hVpyI6eWvwQ","title":"2009 Close Fight Between Rivalry USC and UCLA Football Game","uploaderUrl":"/user/ThatSoCALguy","uploaderName":"ThatSoCALguy","rating":"4","views":"638,032 views","time":"3:19"}],"homepageCache_film_animation":[{"id":"4Hcv-CTnFDQ","title":"Mostly Untitled","uploaderUrl":"/user/flybrewsterfly","uploaderName":"flybrewsterfly","rating":"4.5","views":"1,002,008 views","time":"4:11"},{"id":"4F3voQTg5gQ","title":"REMEMBER ME - \"Ask Rob\" Video #3: Ruby Jerins","uploaderUrl":"/user/SummitScreeningRoom","uploaderName":"SummitScreeningRoom","rating":"5","views":"95,521 views","time":"1:03"},{"id":"exHoV2st-3k","title":"Smooth - Joe Penna","uploaderUrl":"/user/MysteryGuitarMan","uploaderName":"MysteryGuitarMan","rating":"5","views":"2,254,750 views","time":"1:57"},{"id":"BcjV4hLumAc","title":"Microwaving A Box Of Wine! -- FAKE!","uploaderUrl":"/uer/JPizzle1122","uploaderName":"JPizzle1122","rating":"5","views":"307,379 views","time":"3:58"}],"homepageCache_news":[{"id":"5U6fL7Y4BZA","title":"Obama Bows to Japanese Emperor Akihito","uploaderUrl":"/user/UConnRepublicans","uploaderName":"UConnRepublicans","rating":"3.5","views":"341,480 views","time":"3:57"},{"id":"G31aQXH2o60","title":"Dick Cheney In 2012? Daughter Liz Floats Idea","uploaderUrl":"/user/tpmtv","uploaderName":"tpmtv","rating":"2","views":"6,931 views","time":"1:02"},{"id":"ecBPfGMG3Xs","title":"Why You Should Support Reason: Al Sharpton Edition","uploaderUrl":"/user/ReasonTV","uploaderName":"ReasonTV","rating":"5","views":"19,018 views","time":"0:30"},{"id":"Z9eId_9n1NM","title":"Obama's Opening Remarks At Town Hall Meeting In China","uploaderUrl":"/user/NewsPoliticsAmerica","uploaderName":"NewsPoliticsAmerica","rating":"5","views":"15,441 views","time":"10:55"},{"id":"lbgH1NmiDKM","title":"Hillary Clinton: I'm Looking Forward To Talk To Sarah Palin","uploaderUrl":"/user/BangTheNews","uploaderName":"BangTheNews","rating":"5","views":"15,258 views","time":"1:13"}],"homepageCache_music":[{"id":"M11SvDtPBhA","title":"Miley Cyrus - Party In The U.S.A. (Official Video)","uploaderUrl":"/user/hollywoodrecords","uploaderName":"hollywoodrecords","rating":"4.5","views":"800,064,297 views","time":"3:28"},{"id":"uSD4vsh1zDA","title":"The Black Eyed Peas - I Gotta Feeling (Official Music Video)","uploaderUrl":"/user/blackeyedpeasvevo","uploaderName":"blackeyedpeasvevo","rating":"5","views":"625,880,750 views","time":"4:51"},{"id":"psuRGfAaju4","title":"Owl City - Fireflies (Official Music Video)","uploaderUrl":"/user/owlcityvevo","uploaderName":"owlcityvevo","rating":"5","views":"458,102,622 views","time":"3:52"},{"id":"ysSxxIqKNN0","title":"New Divide [Official Music Video] - Linkin Park","uploaderUrl":"/c/LinkinPark","uploaderName":"LinkinPark","rating":"5","views":"529,377,161 views","time":"4:28"},{"id":"p-Z3YrHJ1sU","title":"Edward Maya & Vika Jigulina - Stereo Love (Official Music Video)","uploaderUrl":"/c/spinningrecords","uploaderName":"SpinninRecords","rating":"4.5","views":"527,483,982 views","time":"4:12"},{"id":"bKDdT_nyP54","title":"Akon - Smack That (Official Music Video) ft. Eminem","uploaderUrl":"/user/AkonVEVO","uploaderName":"AkonVEVO","rating":"5","views":"925,549,679 views","time":"4:11"},{"id":"ZaI2IlHwmgQ","title":"The Black Eyed Peas - Pump It (Official Music Video)","uploaderUrl":"/user/blackeyedpeasvevo","uploaderName":"blackeyedpeasvevo","rating":"5","views":"722,568,449 views","time":"3:46"},{"id":"hTWKbfoikeg","title":"Nirvana - Smells Like Teen Spirit (Official Music Video)","uploaderUrl":"/user/NirvanaVEVO","uploaderName":"nirvanavevo","rating":"4.5","views":"1,526,529,038 views","time":"4:38"},{"id":"TxvpctgU_s8","title":"Armin van Buuren feat. Sharon den Adel - In And Out Of Love (Official Music Video)","uploaderUrl":"/c/ArmadaMusic","uploaderName":"ArmadaMusic","rating":"5","views":"263,997,499 views","time":"3:08"},{"id":"WSWrepLjTKc","title":"Kid Cudi vs. Crookers - Day 'n' Night (Official Video)","uploaderUrl":"/c/embassyone","uploaderName":"embassyone","rating":"5","views":"190,593,531 views","time":"3:06"}],"homepageCache_entertainment":[{"id":"ZQY95JSli0o","title":"Republic of Serbia","uploaderUrl":"/user/earthmarathon","uploaderName":"earthmarathon","rating":"5","views":"23,837 views","time":"15:39"},{"id":"1Cm1r3d2Qw4","title":"Toilet Prank","uploaderUrl":"/user/kladblog","uploaderName":"kladblog","rating":"5","views":"19,642,694 views","time":"1:21"},{"id":"ukqrAfuuha8","title":"Hippo and Bully","uploaderUrl":"/user/AngelWynton","uploaderName":"AngelWynton","rating":"4.5","views":"17,367,397 views","time":"2:38"},{"id":"jPkH4TMbeVc","title":"Parov Stelar - Booty Swing (TSC - Forsythe)","uploaderUrl":"/c/takeSomeCrime","uploaderName":"takeSomeCrime","rating":"5","views":"7,877,971 views","time":"3:47"},{"id":"5du1oc0j2KQ","title":"Death Metal Baby!!","uploaderUrl":"/user/RayWilliamJohnson","uploaderName":"RayWilliamJohnson","rating":"5","views":"684,216 views","time":"4:36"}],"homepageCache_featured":[{"id":"O87UmsDvHBU","title":"Hybrid Wars! - Toyota Prius Vs Honda Insight - Part 1","uploaderUrl":"/user/motortrend","uploaderName":"motortrend","rating":4.5,"views":"671,358 views","time":"4:48"},{"id":"pGvmSMCh9ZQ","title":"Waveriders","uploaderUrl":"/user/WorldSportTV","uploaderName":"WorldSportTV","rating":"5","views":"1,902 views","time":"4:46"},{"id":"czWoP7qVNSI","title":"ZOMBIES TAKE OVER YOUTUBE!!!!!!","uploaderUrl":"/user/TheStation","uploaderName":"TheStation","rating":"4.5","views":"3,610,519 views","time":"3:57"},{"id":"ANMrzw7JFzA","title":"Google Chrome OS Demo","uploaderUrl":"/user/googlechrome","uploaderName":"googlechrome","rating":"4","views":"2,558,457 views","time":"11:16"},{"id":"r9YGvLHvUxQ","title":"Motorola Droid Vs. iPhone 3GS","uploaderUrl":"/user/jon4lakers","uploaderName":"jon4lakers","rating":"4.5","views":"1,643,312 views","time":"17:35"},{"id":"43dgFqvtupM","title":"It's Not Me, It's YouTube","uploaderUrl":"/user/winslashfail","uploaderName":"winslashfail","rating":"3","views":"1,266,707 views","time":"0:52"},{"id":"twqM56f_cVo","title":"Parov Stelar - Catgroove (TSC - Forsythe)","uploaderUrl":"/c/takeSomeCrime","uploaderName":"takeSomeCrime","rating":"5","views":"52,971,029 views","time":"3:59"},{"id":"7jjcAuEYW9M","title":"The Duck Song 2","uploaderUrl":"/user/forrestfire101","uploaderName":"forrestfire101","rating":"4.5","views":"112,662,891 views","time":"2:35"},{"id":"35LqQPKylEA","title":"Google Street View Guys","uploaderUrl":"/c/collegehumor","uploaderName":"collegehumor","rating":"5","views":"7,058,823 views","time":"2:36"},{"id":"zOkqH1aSjCY","title":"ZOMG KITTEH!!","uploaderUrl":"/user/RayWilliamJohnson","uploaderName":"RayWilliamJohnson","rating":"5","views":"992,445 views","time":"3:50"},{"id":"tqdZFuGt1I4","title":"Chinese Man Throws Bicycle at Thieves on Scooter!","uploaderUrl":"/user/andrewh23","uploaderName":"andrewh23","rating":"5","views":"613,198 views","time":"0:50"},{"id":"Nb6YeCY0x1k","title":"Very Funny Cats 59","uploaderUrl":"/user/yourfriendy","uploaderName":"yourfriendy","rating":"5","views":"63,486 views","time":"3:38"}],"shareBehaviorServices":{"default":{"MySpace":"http://www.myspace.com/Modules/PostTo/Pages/?t=%title%&u=%url%","Facebook":"http://www.facebook.com/sharer.php?u=%url%&t=%title%","Twitter":"http://www.twitter.com/intent/tweet?text=Check%20this%20video%20out%20--%20%title%%20%url%","Digg":"http://digg.com/submit?phase=2&url=%url%&title=%title%","orkut":"http://www.orkut.com/FavoriteVideos.aspx?u=%url%","Live Spaces":"http://spaces.live.com/BlogIt.aspx?Title=YouTube%20-%20%title%&SourceURL=%url%","Bebo":"http://www.bebo.com/c/share?Url=%url%&Title=%title%","hi5":"http://www.hi5.com/friend/checkViewedVideo.do?t=%title%&url=%url%"},"only_remove":{"Facebook":"http://www.facebook.com/sharer.php","Twitter":"http://www.twitter.com/intent/tweet?text=Check%20this%20video%20out%20--%20%title%%20%url%","hi5":"http://www.hi5.com/friend/checkViewedVideo.do?t=%title%&url=%url%"},"only_add":{"MySpace":"http://www.myspace.com/Modules/PostTo/Pages/?t=%title%&u=%url%","Facebook":"http://www.facebook.com/sharer.php?u=%url%&t=%title%","Twitter":"http://www.twitter.com/intent/tweet?text=Check%20this%20video%20out%20--%20%title%%20%url%","Digg":"http://digg.com/submit?phase=2&url=%url%&title=%title%","orkut":"http://www.orkut.com/FavoriteVideos.aspx?u=%url%","Live Spaces":"http://spaces.live.com/BlogIt.aspx?Title=YouTube%20-%20%title%&SourceURL=%url%","Bebo":"http://www.bebo.com/c/share?Url=%url%&Title=%title%","hi5":"http://www.hi5.com/friend/checkViewedVideo.do?t=%title%&url=%url%","Reddit":"http://www.reddit.com/submit?url=%url%&title=%title%","Pinterest":"http://pinterest.com/pin/create/button/?url=%url%&description=%title%&is_video=true&media=https%3A//i.ytimg.com/vi/%id%/hqdefault.jpg","mailto":"mailto:?body=%url%","Blogger":"http://www.blogger.com/blog-this.g?n=%title%&source=youtube&b=%3Ciframe%20width%3D%22480%22%20height%3D%22270%22%20src%3D%22https%3A//youtube.com/embed/%id%%22%20frameborder%3D%220%22%20allow%3D%22accelerometer%3B%20autoplay%3B%20clipboard-write%3B%20encrypted-media%3B%20gyroscope%3B%20picture-in-picture%22%20allowfullscreen%3E%3C/iframe%3E&eurl=https%3A//i.ytimg.com/vi/%id%/hqdefault.jpg"},"both":{"Reddit":"http://www.reddit.com/submit?url=%url%&title=%title%","Facebook":"http://www.facebook.com/sharer.php","Twitter":"http://www.twitter.com/intent/tweet?text=Check%20this%20video%20out%20--%20%title%%20%url%","mailto":"mailto:?body=%url%","Pinterest":"http://pinterest.com/pin/create/button/?url=%url%&description=%title%&is_video=true&media=https%3A//i.ytimg.com/vi/%id%/hqdefault.jpg","hi5":"http://www.hi5.com/friend/checkViewedVideo.do?t=%title%&url=%url%","Blogger":"http://www.blogger.com/blog-this.g?n=%title%&source=youtube&b=%3Ciframe%20width%3D%22480%22%20height%3D%22270%22%20src%3D%22https%3A//youtube.com/embed/%id%%22%20frameborder%3D%220%22%20allow%3D%22accelerometer%3B%20autoplay%3B%20clipboard-write%3B%20encrypted-media%3B%20gyroscope%3B%20picture-in-picture%22%20allowfullscreen%3E%3C/iframe%3E&eurl=https%3A//i.ytimg.com/vi/%id%/hqdefault.jpg"}}}```

**Comment by EpicSentry** [comment]
Oh crap, sorry I just realized I was behind on a few commits and pulling them has solved this problem.
Sorry for wasting your time with this.

**Comment by ftde0** [comment]
whew! thought it was a new breaking change, glad this got resolved
